### ISSUE TITLE
riscv-clang's LongDoubleWidth is out of date

### ISSUE THREAD

**Issue by markww** [riscvarchive/riscv-clang#3]
While using riscv-clang, it came to my attention that riscv-clang still believes that the size of a long double is 64 bits. This disagrees with riscv-gcc, which treats a long double as if it were 128 bits. This is misleading to a source-to-source transform that I am trying to write.

https://github.com/riscv/riscv-clang/blob/671f3054f5c4e228a937d2705a1bc1c6bf982f82/lib/Basic/Targets.cpp#L4358

**Comment by markww** [comment]
It appears that this issue is not on the active branch, closing.

**Comment by sorear** [comment]
FYI this repository is used by Berkeley for an internal project, and is NOT what external users should be using.  Upstream clang 6 has an unrelated RISC-V port which should be used for new work instead of this repository.

**Comment by markww** [comment]
Good to know, thank you.
